package pbgrafico3;
import java.util.Random;

class Pelea{ //La clase pelea que hace que los golpes se cuenten
    //Atributo
    private int golpes;   
    //Constructor en donde se inicializa la variable compartida
    public Pelea (){
        golpes=0;
    }  
    public int getGolpes(){ //obtiene el numero de golpes
        return golpes;
    }   
    //Metodo sincronizado
    public synchronized void pegar(Boxeador boxeador){
        boxeador.pegar();
        golpes++;   //suma golpes
        System.out.println("Pegada de "+boxeador.getNombre()+" golpes:"+boxeador.getGolpes()); //print de que boxeador pega a quien
    }
    public void reset(){
        golpes=0;
    }
}

class Boxeador extends Thread{
    private String nombre;
    private Pelea pelea;
    private int golpes;
    private Boxeador rival;
    private Random h = new Random();
    /*
    javax.swing.JLabel jLabel1;
    javax.swing.JLabel jLabel2;
    */
    javax.swing.JLabel jLabelx;  //el objeto de la clase JLabel es un componente para colocar texto en un contenedor
    javax.swing.JLabel jLabel3;
    javax.swing.JLabel Apar;
    javax.swing.JLabel Agol;
    
    public Boxeador (String nombre, Pelea pelea,javax.swing.JLabel jLabelx, javax.swing.JLabel jLabel3,javax.swing.JLabel Apar, javax.swing.JLabel Agol){
        this.nombre=nombre;
        this.pelea=pelea;
        this.jLabelx=jLabelx;
        this.jLabel3=jLabel3;
        this.Apar= Apar;
        this.Agol = Agol;
    }
    public Boxeador getRival(){ //obtiene el rival
        return rival;
    } 
    public void setRival(Boxeador rival){ //indica cual es el rival
        this.rival=rival;
    }
    public String getNombre(){ //obtiene nombre del boxeador
        return nombre;
    }
    public int getGolpes(){ //obtiene numero de golpes del boxeador
        return golpes;
    }
    public void pegar(){ //suma los golpes
        golpes++;
    }
    public void AnimacionParado(){  //muestra la animacion de estar parado del boxeador
        Apar.setVisible(true);
        Agol.setVisible(false);
    }
    public void AnimacionGolpe(){ //muestra la animacion de gopear del boxeador
        Apar.setVisible(false);
        Agol.setVisible(true);
    }

    public void run(){
        while(pelea.getGolpes() <100){
            //Para que se sepa el nombre del boxeador que esta dando el golpe, quien pega
            pelea.pegar(this);           
            try{
                Thread.sleep(h.nextInt(1000)+1);
                    this.jLabelx.setText(String.valueOf(this.getGolpes()));
            }
            catch(InterruptedException ex){
        }
    }
    if(golpes>50) //quien llegue primero a 50 gana
        jLabel3.setText("Gana "+nombre);
    if(golpes==50) // si ambos llegan a 50 empate
        jLabel3.setText("Empate");
    this.AnimacionParado(); //ejecuta la animacion de parado
    
}  
}
/////////////////////////////////////////////////////
public class PeleaBox extends javax.swing.JFrame {
    Pelea pelea=new Pelea();
    Boxeador boxeador1, boxeador2;

    public PeleaBox() {
        initComponents();
        setLocationRelativeTo(null);
        boxeador1= new Boxeador("Ryu",pelea,jLabel1,jLabel3,jLabel8,jLabel14); //asignacion de valores al boxeador
         boxeador2= new Boxeador("Ken",pelea,jLabel2,jLabel3,jLabel15,jLabel16);
        boxeador1.AnimacionParado(); //Hice que las animaciones de golpe sean falsas al inicio para que no aparezcan sobrepuestas
        boxeador2.AnimacionParado(); // pone la animacion de de parado en el boxeador
         /*
        boxeador1.RecibeJLabel1(jLabel1);
        boxeador2.RecibeJLabel2(jLabel2);
         */
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    //se asigna imagenes a los JLabell y se agrega texto como el contador de golpes seguidos y quien gana
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbgrafico3/kenGolpe.gif"))); // NOI18N
        jPanel1.add(jLabel16);
        jLabel16.setBounds(270, 90, 150, 110);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbgrafico3/ryuGolpe.gif"))); // NOI18N
        jPanel1.add(jLabel14);
        jLabel14.setBounds(240, 80, 100, 130);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbgrafico3/kenIdle.gif"))); // NOI18N
        jPanel1.add(jLabel15);
        jLabel15.setBounds(340, 90, 70, 110);

        jLabel8.setBackground(new java.awt.Color(255, 153, 102));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbgrafico3/ryuIdle.gif"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(240, 90, 100, 111);

        jLabel13.setFont(new java.awt.Font("Segoe UI Black", 2, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 255));
        jLabel13.setText(":COMBO");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(550, 60, 60, 20);

        jLabel11.setFont(new java.awt.Font("Segoe UI Black", 2, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 255));
        jLabel11.setText("COMBO:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(80, 60, 60, 15);

        jLabel10.setBackground(java.awt.Color.cyan);
        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 255));
        jLabel10.setText("KEN");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(570, 40, 40, 20);

        jLabel7.setBackground(java.awt.Color.cyan);
        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setText("RYU");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(80, 40, 30, 20);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbgrafico3/bbRyu.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(50, 40, 21, 22);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbgrafico3/bbKen.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(610, 40, 20, 22);

        jButton1.setText("Iniciar Pelea");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(280, 230, 120, 25);

        jLabel1.setFont(new java.awt.Font("FZYaoTi", 3, 24)); // NOI18N
        jLabel1.setText("0");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(130, 50, 70, 35);

        jLabel2.setFont(new java.awt.Font("FZYaoTi", 3, 24)); // NOI18N
        jLabel2.setText("0");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(510, 50, 80, 40);

        jLabel3.setFont(new java.awt.Font("FZYaoTi", 3, 24)); // NOI18N
        jLabel3.setText("      F I G H T");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(250, 0, 190, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbgrafico3/stage.gif"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 0, 620, 224);

        jLabel9.setBackground(java.awt.Color.cyan);
        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 255));
        jLabel9.setText("RYU");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(80, 10, 130, 60);

        jLabel12.setFont(new java.awt.Font("Segoe UI Black", 2, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 255));
        jLabel12.setText("COMBO:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(80, 60, 60, 15);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 847, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boxeador1= new Boxeador("Ryu",pelea,jLabel1,jLabel3,jLabel8,jLabel14); //creacion de objetos boxeador para que al presionar start no se
        boxeador2= new Boxeador("Ken",pelea,jLabel2,jLabel3,jLabel15,jLabel16);//rompa el programa
        pelea.reset(); //Se resetea el contador en pelea para que inicie bien el contador si se quiere repetir el programa
        jLabel3.setText("Fight");
        boxeador1.start(); //inicia el hilo de boxeador
        boxeador2.start();
        boxeador1.AnimacionGolpe(); //Se hace el cambio de animaciones de parado a golpes
        boxeador2.AnimacionGolpe(); // realiza la animacion de golpe

        
    }//GEN-LAST:event_jButton1ActionPerformed

    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PeleaBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PeleaBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PeleaBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PeleaBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PeleaBox().setVisible(true);
                
            }
        });
        

        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
